print(3+4)
print(4-3)
print(3*4)
print(4%3)
print(4/3)
print(4**3)
print(4//3)

print('Tishanth')
print('shan')
print('Sri Lanka')
print('i am enjoying 30 dsays of python')

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['asabeneh','python','Finland']))
print(type('tishanth'))
